import {test,expect} from '@playwright/test';

test('catalogue exposes seven specialties but no private question bank',async({request})=>{const response=await request.get('/api/catalog');expect(response.status()).toBe(200);const data=await response.json();expect(data.specialties).toHaveLength(7);expect(JSON.stringify(data)).not.toMatch(/correctOptionId|"answer"|"stem"/);const me=await request.get('/api/me');expect(me.status()).toBe(200);expect((await me.json()).user).toBeNull();});
test('home has clear specialty choices without browser errors',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('h1')).toBeVisible();for(const text of ['Ciberseguridad','Desarrollo Web','Accounting'])await expect(page.getByText(text,{exact:true}).first()).toBeVisible();expect(errors).toEqual([]);});
test('registration asks only identity and initial specialty, gates unconfigured backend',async({page,request})=>{const catalog=await(await request.get('/api/catalog')).json();await page.goto('/registro');for(const text of ['Nombre y apellidos','Sección o grupo','Correo personal','Especialidad para comenzar'])await expect(page.getByLabel(text,{exact:true})).toBeVisible();await expect(page.locator('input[type=password]')).toHaveCount(0);await expect(page.getByLabel('Nombre de usuario',{exact:true})).toHaveCount(0);if(!catalog.configured||!catalog.registrationOpen)await expect(page.getByRole('button',{name:'Verificar mi correo',exact:true})).toBeDisabled();});
test('verification GET without token never activates an account or submits a mutation',async({page})=>{const writes:string[]=[];page.on('request',r=>{if(['POST','PATCH','DELETE'].includes(r.method()))writes.push(r.url());});await page.goto('/verificar');await expect(page.getByRole('heading',{name:'Confirme su correo',exact:true})).toBeVisible();await expect(page.getByText(/Abra el enlace completo que recibió por correo/)).toBeVisible();await expect(page.getByRole('button',{name:'Verificar mi correo',exact:true})).toBeDisabled();expect(writes).toEqual([]);});
test('installation guidance modal closes with Escape (UI fixture, not Auth proof)',async({page})=>{await page.route('**/api/me',route=>route.fulfill({json:{user:{id:'10000000-0000-4000-8000-000000000001',email:'ui@example.test',name:'Usuario UI',group:'QA',specialty:'3006',theme:'light',owner:false,scope:'student'}}}));await page.goto('/app');const button=page.getByRole('button',{name:/Cómo instalar|Instalar aplicación/});await expect(button).toBeVisible();await button.click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('button',{name:'Entendido',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);});
test('theme persists after reload and supports light and dark',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Activar modo oscuro',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.getByRole('button',{name:'Activar modo claro',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');});
for(const width of [360,390,768,1440])test(`public routes fit a ${width}px viewport`,async({page})=>{await page.setViewportSize({width,height:900});for(const path of ['/','/registro','/ingresar','/privacidad','/condiciones']){await page.goto(path);await expect(page.locator('h1').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);}});
test('sensitive source paths never expose SQL, secrets or bank content',async({request})=>{for(const path of ['/content-source/especialidades/3006/bank.json','/.env','/supabase/migrations/202609240001_identity.sql']){const response=await request.get(path);const body=await response.text();expect(body).not.toMatch(/CREATE TABLE private\.accounts|SUPABASE_SERVICE_ROLE_KEY\s*=|"answer"\s*:\s*[0-3]|"stem"\s*:/i);}});
test('cross-origin login mutation is rejected with a safe response',async({request})=>{const response=await request.post('/api/auth/login',{headers:{Origin:'https://untrusted.example','Content-Type':'application/json'},data:{email:'nobody@example.test',password:'not-a-real-password'}});expect(response.status()).toBeGreaterThanOrEqual(400);const body=await response.text();expect(body).not.toMatch(/service_role|SUPABASE_SERVICE_ROLE_KEY|at .*\.tsx?:\d|postgres:\/\//);expect(JSON.parse(body)).toHaveProperty('error');});
