import{describe,it,expect}from'vitest';import{readFileSync,readdirSync,statSync}from'node:fs';import path from'node:path';import{createHash}from'node:crypto';
const source=path.join(process.cwd(),'content-source'),json=(name:string)=>JSON.parse(readFileSync(path.join(source,name),'utf8')),catalogue=json('catalogo_original.json'),hashes=json('SHA256SUMS.json'),blueprints=json('blueprints.json');
const files=(dir:string):string[]=>readdirSync(dir).flatMap(n=>statSync(path.join(dir,n)).isDirectory()?files(path.join(dir,n)):[path.join(dir,n)]);
describe('immutable original curriculum',()=>{
it('has seven specialties,35 forms and2100 complete questions',()=>{expect(Object.keys(catalogue).sort()).toEqual(['2017','3001','3002','3006','3010','3016','3019']);let total=0;for(const[code,s]of Object.entries(catalogue)as[string,any][]){const bank=json(`especialidades/${code}/bank.json`),ids=new Set();expect(Object.keys(bank).sort()).toEqual(['A','B','C','D','E']);for(const[form,questions]of Object.entries(bank)as[string,any[]][]){expect(questions).toHaveLength(60);for(const q of questions){expect(q.id).toMatch(new RegExp(`^${form}\\d+$`));expect(ids.has(q.id)).toBe(false);ids.add(q.id);expect(q.options).toHaveLength(4);expect(new Set(q.options).size).toBe(4);expect(q.options.every((x:string)=>typeof x==='string'&&x.trim())).toBe(true);expect(Number.isInteger(q.answer)&&q.answer>=0&&q.answer<4).toBe(true);expect(Number.isInteger(q.area)&&q.area>=0&&q.area<s.areas.length).toBe(true);expect(q.stem.trim().length).toBeGreaterThan(0);expect(q.explanation.trim().length).toBeGreaterThan(0);total++;}}}expect(total).toBe(2100);});
it.each(Object.entries(hashes))('matches original SHA256 %s',(relative,expected)=>{expect(createHash('sha256').update(readFileSync(path.join(source,relative))).digest('hex')).toBe(expected);});
it('has14 genuine PDF signatures',()=>{const pdfs=files(path.join(source,'especialidades')).filter(f=>f.endsWith('.pdf'));expect(pdfs).toHaveLength(14);for(const f of pdfs)expect(readFileSync(f).subarray(0,5).toString()).toBe('%PDF-');});
it('all35 blueprints preserve the exact indicator-area-difficulty quota',()=>{for(const s of blueprints.specialties){const bank=json(s.source_bank);for(const f of s.forms){const expected=new Map<string,number>();for(const q of bank[f.form]){const k=JSON.stringify([q.area,q.indicator,q.difficulty]);expected.set(k,(expected.get(k)||0)+1);}const actual=new Map<string,number>(f.quotas.map((q:any)=>[JSON.stringify([q.area,q.indicator,q.difficulty]),q.count]));expect(actual).toEqual(expected);expect([...actual.values()].reduce((a,b)=>a+b,0)).toBe(60);}}});
it('does not publish private banks or original PDF',()=>{for(const f of files(path.join(process.cwd(),'public'))){expect(f).not.toMatch(/bank\.json$|\.pdf$|\.sql$|\.pem$|\.env/);if(/\.(json|js|webmanifest)$/.test(f))expect(readFileSync(f,'utf8')).not.toMatch(/"answer"\s*:\s*[0-3]/);}});
});
