import {writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {main,flag,option,need,destination,admin,sha,assertDatabaseDestination} from './shared';
import {encrypt,format,pgCommand,type Backup} from './backup-lib';
main(async()=>{if(flag('help')){console.log('pnpm backup:run [--output=backups/archivo.ptbackup]. Cifra PostgreSQL y PDF con AES-256-GCM; custodie la clave por separado.');return;}const{ref}=destination();assertDatabaseDestination(need('DATABASE_URL'),ref);const client=admin();const data=await pgCommand('pg_dump',['--format=custom','--no-owner','--no-acl','--schema=public','--schema=private','--schema=auth','--schema=storage','--schema=migration_meta'],need('DATABASE_URL'));
 const archive:Backup={format,createdAt:new Date().toISOString(),sourceProject:ref,database:{sha256:sha(data),base64:data.toString('base64')},objects:[],notes:['Configuración Auth, claves de cifrado, Vault, dominios y cron se reconstruyen desde proyecto y secretos custodiados.','Incluye identidades y datos privados. Mantener archivo y clave separados.']};
 async function walk(prefix=''){for(let offset=0;;offset+=100){const{data:files,error}=await client.storage.from('study-materials').list(prefix,{limit:100,offset,sortBy:{column:'name',order:'asc'}});if(error)throw error;for(const file of files??[]){const path=prefix?`${prefix}/${file.name}`:file.name;if(!file.id){await walk(path);continue;}const{data:blob,error:de}=await client.storage.from('study-materials').download(path);if(de||!blob)throw new Error('No se completó la copia de Storage.');const bytes=Buffer.from(await blob.arrayBuffer());archive.objects.push({bucket:'study-materials',path,sha256:sha(bytes),base64:bytes.toString('base64')});}if((files?.length??0)<100)break;}}
 await walk();const output=resolve(option('output')??`backups/${new Date().toISOString().replace(/[:.]/g,'-')}.ptbackup`);await mkdir(resolve(output,'..'),{recursive:true});const encrypted=encrypt(archive);await writeFile(output,encrypted,{mode:0o600});console.log(`Respaldo cifrado: ${output}. Objetos: ${archive.objects.length}. SHA256: ${sha(encrypted)}. Aún debe ensayarse restauración aislada.`);
});
