import {spawn} from 'node:child_process';
import {createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import {need} from './shared';
export const format='practicatecnica-backup-v1';
export interface Backup{format:string;createdAt:string;sourceProject:string;database:{sha256:string;base64:string};objects:{bucket:string;path:string;sha256:string;base64:string}[];notes:string[];}
export function key(){const key=Buffer.from(need('BACKUP_ENCRYPTION_KEY'),'base64');if(key.length!==32)throw new Error('BACKUP_ENCRYPTION_KEY requiere 32 bytes en base64.');return key;}
export function encrypt(data:Backup){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv);const body=Buffer.concat([cipher.update(Buffer.from(JSON.stringify(data))),cipher.final()]);return Buffer.concat([Buffer.from('PTBK1'),iv,cipher.getAuthTag(),body]);}
export function decrypt(data:Buffer):Backup{if(data.subarray(0,5).toString()!=='PTBK1')throw new Error('Formato de respaldo no reconocido.');const decipher=createDecipheriv('aes-256-gcm',key(),data.subarray(5,17));decipher.setAuthTag(data.subarray(17,33));return JSON.parse(Buffer.concat([decipher.update(data.subarray(33)),decipher.final()]).toString())as Backup;}
export function pgEnv(url:string){const u=new URL(url);return{...process.env,PGHOST:u.hostname,PGPORT:u.port||'5432',PGDATABASE:decodeURIComponent(u.pathname.slice(1)),PGUSER:decodeURIComponent(u.username),PGPASSWORD:decodeURIComponent(u.password),PGSSLMODE:['localhost','127.0.0.1'].includes(u.hostname)?'disable':'verify-full'};}
export function pgCommand(command:string,args:string[],url:string,input?:Buffer):Promise<Buffer>{return new Promise((ok,fail)=>{const child=spawn(command,args,{env:pgEnv(url),stdio:['pipe','pipe','pipe']});const chunks:Buffer[]=[];let total=0;child.stdout.on('data',(chunk:Buffer)=>{total+=chunk.length;if(total>200*1024*1024){child.kill();fail(new Error('Respaldo supera 200 MB: necesita una solución de streaming administrada.'));}else chunks.push(chunk);});child.stderr.resume();child.on('error',()=>fail(new Error(`No se pudo ejecutar ${command}. Instale PostgreSQL cliente compatible con el servidor.`)));child.on('exit',code=>code===0?ok(Buffer.concat(chunks)):fail(new Error(`${command} falló (${code}). Verifique conexión, permisos y versión; no se generó respaldo válido.`)));if(input)child.stdin.end(input);else child.stdin.end();});}
