import {main,flag,authorizeWrite,database,need} from './shared';
main(async()=>{
 if(flag('help')){console.log('pnpm mail:configure --apply --project-ref=REF. Configura SMTP Auth y Cron. Despliegue primero con mail:deploy.');return;}const{ref,url}=authorizeWrite();const from=need('MAIL_FROM'),address=from.match(/<([^>]+)>/)?.[1]??from;if(!address.includes('@'))throw new Error('MAIL_FROM debe ser una dirección del dominio verificado.');
 const response=await fetch(`https://api.supabase.com/v1/projects/${ref}/config/auth`,{method:'PATCH',headers:{Authorization:`Bearer ${need('SUPABASE_ACCESS_TOKEN')}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(30000),body:JSON.stringify({smtp_host:'smtp.resend.com',smtp_port:'465',smtp_user:'resend',smtp_pass:need('RESEND_API_KEY'),smtp_admin_email:address,smtp_sender_name:'PracTICAtecnica.com'})});if(!response.ok)throw new Error(`No se pudo configurar SMTP Auth (${response.status}).`);
 const db=database();await db.connect();try{await db.query('begin');await db.query('create extension if not exists pg_cron');await db.query('create extension if not exists pg_net with schema extensions');await db.query('create extension if not exists supabase_vault with schema vault');
  for(const[name,value]of[['practicatecnica_mail_worker_url',new URL('/functions/v1/mail-worker',url).toString()],['practicatecnica_mail_worker_secret',need('MAIL_WORKER_SECRET')]]){const found=await db.query('select id from vault.secrets where name=$1',[name]);if(found.rowCount)await db.query('select vault.update_secret($1,$2)',[found.rows[0].id,value]);else await db.query('select vault.create_secret($1,$2)',[value,name]);}
  await db.query(`create or replace function private.dispatch_mail_tick() returns bigint language plpgsql security definer set search_path='' as $$ declare endpoint text; secret text; request_id bigint; begin select decrypted_secret into endpoint from vault.decrypted_secrets where name='practicatecnica_mail_worker_url'; select decrypted_secret into secret from vault.decrypted_secrets where name='practicatecnica_mail_worker_secret'; if endpoint is null or secret is null then raise exception 'worker_not_configured'; end if; select net.http_post(url:=endpoint,headers:=jsonb_build_object('Content-Type','application/json','Authorization','Bearer '||secret),body:='{}'::jsonb,timeout_milliseconds:=55000) into request_id; return request_id; end $$`);
  await db.query('revoke all on function private.dispatch_mail_tick() from public,anon,authenticated');await db.query("select cron.unschedule(jobid) from cron.job where jobname='practicatecnica-mail-minute'");await db.query("select cron.schedule('practicatecnica-mail-minute','* * * * *','select private.dispatch_mail_tick()')");await db.query('commit');
 }catch(e){await db.query('rollback');throw e;}finally{await db.end();}
 console.log('SMTP y Cron configurados: un trabajo por minuto. Debe verificar dominio Resend, desplegar Edge Function y comprobar entrega autorizada; configurar no acredita recepción.');
});
